version: '2'
services:
  elasticsearch:
    build: elasticsearch
    volumes:
      - ./elasticsearch/es-data/:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  kibana:
    build: kibana
    # volumes:
      # - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  jupyter:
    build: client
    ports:
      - 8888:8888
    volumes:
      - ./client:/analysis
    working_dir: /analysis